### ISSUE TITLE
Error while running CoREATACPredictor-singularity.sh

### ISSUE THREAD

**Issue by samiraghazali** [UcarLab/CoRE-ATAC#4]
I am trying to use CoRE-ATAC. After feature extraction, I run CoREATACPredictor-singularity.sh and I have this error : 

2022-02-21 13:33:03.907526: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /.singularity.d/libs
2022-02-21 13:33:03.913088: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2022-02-21 13:33:03.913183: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (samira-VirtualBox): /proc/driver/nvidia/version does not exist
2022-02-21 13:33:03.913496: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2022-02-21 13:33:03.930392: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2294685000 Hz
2022-02-21 13:33:03.930670: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f709c000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-02-21 13:33:03.930737: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version

Would you please tell me how can I correct it ? Thank you in advance 

Samira GHAZALI

**Comment by ajt986** [comment]
Hello,

I think you'll need to build the singularity image on your system. The definition file is available here:

https://github.com/UcarLab/CoRE-ATAC/blob/master/singularity/CoRE-ATAC-FeaturePredictor.def

Download this definition file and generate the singularity image using:
`sudo singularity build <path to .sif file to generate> <path to CoRE-ATAC-FeaturePredictor.def>`

You can test the prediction part immediately after the image is built since the HOMER installation steps are only used for feature extraction. Let me know if this works. If it doesn't, then my next guess will be to change the Tensorflow installation line: 

`yes | pip3 install tensorflow==2.2` 

in the definition file.

**Comment by samiraghazali** [comment]
Hello, 
Thank you for your reply. The command doesn't work for me. I got an error : FATAL:   While performing build: conveyor failed to get: while getting image info: request did not succeed: architecture not specified (500 Internal Server Error) 

am I going to exrase the old sif file that I used to build the sandbox by running this command? Or should it be in a different folder? 
Thank you again

Samira GHAZALI

**Comment by ajt986** [comment]
If you try to build using a definition file with just:

```
Bootstrap: library
From: ubuntu:18.04
```

Do you still see this error? It looks like this error has something to do with not being able to pull the ubuntu base image. If this is the case, then you'll need to pull an ubuntu base image (doesn't necessarily have to be 18.04) with whichever way your version of singularity is configured. 

You will be overwriting the .sif if you give it the same path, but hopefully the the new image will allow for running the prediction script without error. Just be sure the use the .sif and not the sandbox directory for prediction. The feature extraction step doesn't need to be repeated if it already ran successfully.

**Comment by samiraghazali** [comment]
Hello, 

Thank you a lot for your response. I am using singlarity version 3.3.0 . When I changed ubuntu version to 16.04, it does work better except for python3. I obtain this error :  E: Unable to locate package python3.6
E: Couldn't find any package by glob 'python3.6'
E: Couldn't find any package by regex 'python3.6'
FATAL:   failed to execute %post proc: exit status 100
FATAL:   While performing build: while running engine: exit status 255. I think because this version of python isn't available in ubuntu 16.04 . 

When I used as a parameter : From: ubuntu:latest. I got the error : 

INFO:    Starting build...
INFO:    Downloading library image
singularity image-build: relocation error: /lib/x86_64-linux-gnu/libnss_files.so.2: symbol __nss_files_fopen version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
FATAL:   While performing build: while running engine: exit status 127

Do I need to install a specific version of singularity to run it ? Noting that I used the same version and configuration to build the sandbox and do the feature extraction step. 
Thank you again for your help, I would like really to use your tool, which looks amazing, in my project. 

Best regards,

Samira GHAZALI

**Comment by ajt986** [comment]
Hi Samira,

Can you please try using this image file from the pre-release ( https://github.com/UcarLab/CoRE-ATAC/releases/tag/v1.2.1 ) and see if it works? I just tested this image on a system using CPU only and it worked after configuring packages in the definition file.

**Comment by samiraghazali** [comment]
Hello,

Thank you for your reply again. Unfortunately, I couldn't run the script using singularity. Thus, I installed the needed libraries in my computer and called CoREATAC-PredictionTool.py. Using a small sample, the prediction worked good. 

It may be important to note that I put in comment two command lines that aim to filter chrX and Y in getMetaData function from TensorLoader.py script, because it changes np.array dimensions and introduces error in the return step. 

Thank you again for your help. 

Samira
